//! Localhost HTTP bridge between the browser extension and the desktop app.
//!
//! Replaces the previous Chrome native-messaging path, which required
//! hard-coding extension IDs in an OS-installed manifest. This bridge listens
//! on `127.0.0.1:<port>` and authenticates extension requests with a single
//! random token that the user pairs once via the app's settings UI.
//!
//! The token is regenerated by hand from the settings (or by deleting it from
//! `settings.json`); the port is picked at first launch from a small range
//! and persisted so the extension always knows where to connect.
//!
//! Endpoints:
//!
//! * `GET  /v1/health`  — unauthenticated; returns `{ ok, version }` so the
//!                         extension can detect that the app is running.
//! * `POST /v1/enqueue` — authenticated; same payload as the legacy native
//!                         host accepted (`ExtensionPayload`). Validates the
//!                         URL, writes cookies + metadata to disk, then queues
//!                         the URL through `external_url::handle_external_url`.

use std::net::SocketAddr;
use std::sync::Arc;

use axum::{
    extract::State,
    http::{HeaderMap, Method, StatusCode},
    response::{IntoResponse, Response},
    routing::{get, post},
    Json, Router,
};
use base64::Engine;
use serde::{Deserialize, Serialize};
use socket2::{Domain, Protocol, Socket, Type};
use tauri::AppHandle;
use tokio::net::TcpListener;
use tower_http::cors::{Any, CorsLayer};

use crate::extension_storage::{
    cookie_limit, write_extension_cookies, write_extension_metadata, ExtensionCookie,
    ExtensionPayload,
};
use crate::storage::config;

/// Range of ports we'll try when picking a fresh `bridge.port`. Chosen above
/// the most common dev-server / Vite ranges so collisions are rare.
const PORT_RANGE: std::ops::Range<u16> = 47720..47730;

#[derive(Clone)]
pub struct BridgeState {
    pub app: AppHandle,
    /// Authoritative copy of the bearer token, kept in `Arc` so cloning the
    /// state for each handler doesn't allocate, and so reading it is lock-free.
    pub token: Arc<String>,
}

#[derive(Debug, Serialize)]
struct HealthResponse {
    ok: bool,
    version: &'static str,
}

#[derive(Debug, Serialize)]
struct EnqueueResponse {
    ok: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    code: Option<&'static str>,
    #[serde(skip_serializing_if = "Option::is_none")]
    message: Option<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct EnqueueRequest {
    #[serde(flatten)]
    payload: ExtensionPayload,
    #[serde(default)]
    protocol_version: Option<u32>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct CookiesRequest {
    #[serde(default)]
    cookies: Vec<ExtensionCookie>,
    #[serde(default)]
    protocol_version: Option<u32>,
}

const HOST_MAX_PROTOCOL_VERSION: u32 = 1;

/// Generate a random bearer token (32 bytes, URL-safe base64, no padding).
pub fn generate_token() -> String {
    let mut buf = [0u8; 32];
    rand::Rng::fill_bytes(&mut rand::rng(), &mut buf);
    base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(buf)
}

/// Bind a TCP listener on `127.0.0.1:port` with `SO_REUSEADDR` enabled so
/// the port can be re-bound immediately across app restarts (the previous
/// socket stays in `TIME_WAIT` for ~60 s otherwise, which would otherwise
/// kick us off our persisted port and force re-pairing).
fn bind_with_reuse(port: u16) -> std::io::Result<TcpListener> {
    let addr: SocketAddr = ([127, 0, 0, 1], port).into();
    let socket = Socket::new(Domain::IPV4, Type::STREAM, Some(Protocol::TCP))?;
    socket.set_reuse_address(true)?;
    socket.set_nonblocking(true)?;
    socket.bind(&addr.into())?;
    socket.listen(128)?;
    let std_listener: std::net::TcpListener = socket.into();
    TcpListener::from_std(std_listener)
}

/// Try to bind a free TCP listener — first the persisted port, then the
/// preferred range, finally `0` (OS-picked) as last resort.
async fn bind_listener(preferred: u16) -> std::io::Result<(u16, TcpListener)> {
    if preferred != 0 {
        if let Ok(listener) = bind_with_reuse(preferred) {
            return Ok((preferred, listener));
        }
    }

    for port in PORT_RANGE {
        if let Ok(listener) = bind_with_reuse(port) {
            return Ok((port, listener));
        }
    }

    let listener = bind_with_reuse(0)?;
    let port = listener.local_addr()?.port();
    Ok((port, listener))
}

/// Ensure `settings.bridge.{token,port}` are populated and persisted.
/// Returns the resolved (token, port) pair to use for this run.
fn ensure_bridge_settings(
    app: &AppHandle,
    bound_port: u16,
) -> anyhow::Result<(String, u16)> {
    let mut settings = config::load_settings(app);
    let mut dirty = false;

    if settings.bridge.token.trim().is_empty() {
        settings.bridge.token = generate_token();
        dirty = true;
    }
    if settings.bridge.port != bound_port {
        settings.bridge.port = bound_port;
        dirty = true;
    }

    if dirty {
        config::save_settings(app, &settings)?;
    }

    Ok((settings.bridge.token, settings.bridge.port))
}

/// Spawn the localhost bridge in a background tokio task.
///
/// Returns once the listener has been bound (so the port is known and
/// persisted), then continues serving on the spawned task. Errors during
/// binding are logged but never propagated up — the deep-link path remains
/// usable as a fallback.
pub async fn spawn(app: AppHandle) {
    let settings = config::load_settings(&app);

    if !settings.bridge.enabled {
        tracing::info!("local bridge disabled by settings; not starting HTTP server");
        return;
    }

    let preferred_port = settings.bridge.port;
    let (port, listener) = match bind_listener(preferred_port).await {
        Ok(pair) => pair,
        Err(error) => {
            tracing::warn!(
                "failed to bind local bridge on 127.0.0.1: {} — extension cookie path disabled",
                error
            );
            return;
        }
    };

    let (token, _port) = match ensure_bridge_settings(&app, port) {
        Ok(pair) => pair,
        Err(error) => {
            tracing::warn!("failed to persist bridge settings: {}", error);
            return;
        }
    };

    let state = BridgeState {
        app: app.clone(),
        token: Arc::new(token),
    };

    let cors = CorsLayer::new()
        // The token is the actual auth boundary, so we accept any browser
        // origin (extension or webpage). Requests without a valid bearer are
        // still rejected by the handler.
        .allow_origin(Any)
        .allow_methods([Method::GET, Method::POST, Method::OPTIONS])
        .allow_headers(Any);

    let router = Router::new()
        .route("/v1/health", get(health))
        .route("/v1/enqueue", post(enqueue))
        .route("/v1/cookies", post(cookies_export))
        .with_state(state)
        .layer(cors);

    tracing::info!("local bridge listening on http://127.0.0.1:{port}");

    tokio::spawn(async move {
        if let Err(error) = axum::serve(listener, router).await {
            tracing::warn!("local bridge stopped: {error}");
        }
    });
}

async fn health() -> Json<HealthResponse> {
    Json(HealthResponse {
        ok: true,
        version: env!("CARGO_PKG_VERSION"),
    })
}

fn unauthorized() -> Response {
    let body = Json(EnqueueResponse {
        ok: false,
        code: Some("UNAUTHORIZED"),
        message: Some("Invalid or missing bearer token".to_string()),
    });
    (StatusCode::UNAUTHORIZED, body).into_response()
}

fn check_bearer(headers: &HeaderMap, expected: &str) -> bool {
    let header = match headers.get("authorization") {
        Some(v) => v,
        None => return false,
    };
    let raw = match header.to_str() {
        Ok(s) => s,
        Err(_) => return false,
    };
    let provided = match raw.strip_prefix("Bearer ").or_else(|| raw.strip_prefix("bearer ")) {
        Some(s) => s.trim(),
        None => return false,
    };
    constant_time_eq::constant_time_eq(provided.as_bytes(), expected.as_bytes())
}

async fn enqueue(
    State(state): State<BridgeState>,
    headers: HeaderMap,
    Json(request): Json<EnqueueRequest>,
) -> Response {
    if !check_bearer(&headers, &state.token) {
        return unauthorized();
    }

    if let Some(client_version) = request.protocol_version {
        if client_version > HOST_MAX_PROTOCOL_VERSION {
            return error_response(
                StatusCode::BAD_REQUEST,
                "UNSUPPORTED_PROTOCOL",
                format!(
                    "Extension protocol v{client_version} is newer than host v{HOST_MAX_PROTOCOL_VERSION}. Please update OmniGet."
                ),
            );
        }
    }

    let payload = request.payload;

    if !crate::external_url::is_external_url(&payload.url) {
        return error_response(
            StatusCode::BAD_REQUEST,
            "INVALID_URL",
            "The requested URL is invalid".to_string(),
        );
    }

    if let Some(ref cookies) = payload.cookies {
        if cookies.len() > cookie_limit() {
            return error_response(
                StatusCode::BAD_REQUEST,
                "TOO_MANY_COOKIES",
                format!(
                    "Request contains {} cookies; max allowed is {}",
                    cookies.len(),
                    cookie_limit()
                ),
            );
        }
        if !cookies.is_empty() {
            if let Err(error) = write_extension_cookies(cookies) {
                tracing::warn!("failed to write extension cookies: {error}");
            }
        }
    }

    if payload.referer.is_some()
        || payload.headers.is_some()
        || payload.media_type.is_some()
        || payload.title.is_some()
        || payload.thumbnail.is_some()
        || payload.open_app.is_some()
        || payload.page_url.is_some()
        || payload.user_agent.is_some()
    {
        if let Err(error) = write_extension_metadata(&payload) {
            tracing::warn!("failed to write extension metadata: {error}");
        }
    }

    let app = state.app.clone();
    let url = payload.url.clone();
    tauri::async_runtime::spawn(async move {
        if let Err(error) =
            crate::external_url::handle_external_url(&app, url, "bridge").await
        {
            tracing::warn!("failed to handle bridge URL: {error}");
        }
    });

    let body = Json(EnqueueResponse {
        ok: true,
        code: None,
        message: None,
    });
    (StatusCode::OK, body).into_response()
}

async fn cookies_export(
    State(state): State<BridgeState>,
    headers: HeaderMap,
    Json(request): Json<CookiesRequest>,
) -> Response {
    if !check_bearer(&headers, &state.token) {
        return unauthorized();
    }

    if let Some(client_version) = request.protocol_version {
        if client_version > HOST_MAX_PROTOCOL_VERSION {
            return error_response(
                StatusCode::BAD_REQUEST,
                "UNSUPPORTED_PROTOCOL",
                format!(
                    "Extension protocol v{client_version} is newer than host v{HOST_MAX_PROTOCOL_VERSION}. Please update OmniGet."
                ),
            );
        }
    }

    if request.cookies.len() > cookie_limit() {
        return error_response(
            StatusCode::BAD_REQUEST,
            "TOO_MANY_COOKIES",
            format!(
                "cookies:export contains {} cookies; max is {}",
                request.cookies.len(),
                cookie_limit()
            ),
        );
    }

    if !request.cookies.is_empty() {
        if let Err(error) = write_extension_cookies(&request.cookies) {
            return error_response(
                StatusCode::INTERNAL_SERVER_ERROR,
                "WRITE_FAILED",
                format!("write extension cookies: {error}"),
            );
        }
    }

    let body = Json(EnqueueResponse {
        ok: true,
        code: None,
        message: None,
    });
    (StatusCode::OK, body).into_response()
}

fn error_response(status: StatusCode, code: &'static str, message: String) -> Response {
    let body = Json(EnqueueResponse {
        ok: false,
        code: Some(code),
        message: Some(message),
    });
    (status, body).into_response()
}

pub fn build_pairing_url(port: u16) -> String {
    format!("http://127.0.0.1:{port}")
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::http::HeaderValue;

    fn header_with_auth(value: &str) -> HeaderMap {
        let mut headers = HeaderMap::new();
        headers.insert(
            "authorization",
            HeaderValue::from_str(value).expect("valid header"),
        );
        headers
    }

    #[test]
    fn token_is_url_safe_base64_with_no_padding() {
        let t = generate_token();
        assert!(t.len() >= 40);
        assert!(!t.contains('+'));
        assert!(!t.contains('/'));
        assert!(!t.contains('='));
    }

    #[test]
    fn check_bearer_accepts_valid_token() {
        let headers = header_with_auth("Bearer abc.def-ghi");
        assert!(check_bearer(&headers, "abc.def-ghi"));
    }

    #[test]
    fn check_bearer_is_case_insensitive_on_scheme() {
        let headers = header_with_auth("bearer abc");
        assert!(check_bearer(&headers, "abc"));
    }

    #[test]
    fn check_bearer_rejects_missing_header() {
        let headers = HeaderMap::new();
        assert!(!check_bearer(&headers, "abc"));
    }

    #[test]
    fn check_bearer_rejects_wrong_token() {
        let headers = header_with_auth("Bearer different");
        assert!(!check_bearer(&headers, "abc"));
    }

    #[test]
    fn check_bearer_rejects_missing_scheme_prefix() {
        let headers = header_with_auth("abc");
        assert!(!check_bearer(&headers, "abc"));
    }

    #[test]
    fn build_pairing_url_uses_loopback_address() {
        assert_eq!(build_pairing_url(47720), "http://127.0.0.1:47720");
    }
}
